version: '3'

services:
  plugin-services:
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      - plugin_net
      - docker_default
    ports:
      - "8090:8000"
    volumes:
      - ./data:/app/data
      - ./swagger.html:/app/swagger/swagger.html
      - ./sql_plugin.yaml:/app/swagger/sql_plugin.yaml
    environment:
      - API_KEY=${API_KEY}
      - DATABASE_CONFIGS=${DATABASE_CONFIGS}
      - FILE_EXPIRY_HOURS=${FILE_EXPIRY_HOURS}
      - WORKERS=${WORKERS}
      - THREADS=${THREADS}
      - TIMEOUT=${TIMEOUT}
      - ALLOWED_OUTPUT_TYPES=file_md,file_csv,out_md,out_json
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:alpine
    networks:
      - plugin_net
      - docker_default
    ports:
      - "0.0.0.0:6:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
      - ./swagger.html:/app/swagger/swagger.html
      - ./sql_plugin.yaml:/app/swagger/sql_plugin.yaml
    depends_on:
      plugin-services:
        condition: service_healthy
    restart: always

networks:
  plugin_net:
    driver: bridge
  docker_default:
    external: true